<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ruang_detail_model extends CI_Model
{

    public $table = 'ruang_detail';
    public $id = 'id_ruang_detail';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_aset_sub', $q);
    $this->db->or_like('seri', $q);
    $this->db->or_like('nama_aset', $q);
    $this->db->or_like('tanggal_input', $q);
    $this->db->or_like('tahun', $q);
    $this->db->or_like('merk_aset', $q);
    $this->db->or_like('satuan_aset', $q);
    $this->db->or_like('penguasaan', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_aset_sub', $q);
    $this->db->or_like('seri', $q);
    $this->db->or_like('nama_aset', $q);
    $this->db->or_like('tanggal_input', $q);
    $this->db->or_like('tahun', $q);
    $this->db->or_like('merk_aset', $q);
    $this->db->or_like('satuan_aset', $q);
    $this->db->or_like('penguasaan', $q);
    $this->db->or_like('keterangan', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

     function get_all_ruang_detail()
    {
        $this->db->order_by('id_ruang_detail', 'asc');
        return $this->db->get('ruang_detail')->result_array();
    }

    public function getAllData($table)
    {
        return $this->db->get($table);
    }

    function get_detail($table,$id_table,$id) {
        $query = $this->db->get_where($table, array($id_table => $id));
        return $query;
    }
    
    function add_ruang($params)
    {
        $this->db->insert('ruang_detail',$params);
        return $this->db->insert_id();
    }

    function get_stok($kode_barang)
    {
        return $this->db->get_where('barang',array('id_barang'=>$kode_barang))->result();
    }

}

/* End of file Barang_model.php */
/* Location: ./application/models/Barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:51 */
/* http://harviacode.com */